/**
 * Medical Report Generator Service
 * Generates structured medical reports from consultation data
 */

export const generateReportMarkdown = (data) => {
  const { patientName, date, conditions, specialties, medicines, selfCare, followUp, ragSources } = data;
  
  let md = `# Medical Consultation Report\n\n`;
  md += `**Patient:** ${patientName || 'Anonymous'}\n`;
  md += `**Date:** ${date || new Date().toLocaleString()}\n`;
  md += `**Status:** AI-Assisted Preliminary Assessment\n\n`;
  md += `---\n\n`;
  
  md += `## ⚠️ Important Disclaimer\n\n`;
  md += `This report is generated by an AI-assisted healthcare system and is **NOT a definitive medical diagnosis**. `;
  md += `It provides preliminary assessment based on reported symptoms and medical knowledge retrieval. `;
  md += `Always consult a qualified healthcare professional for accurate diagnosis and treatment.\n\n`;
  md += `---\n\n`;
  
  md += `## Possible Conditions (AI Assessment)\n\n`;
  if (conditions && conditions.length > 0) {
    conditions.forEach((c, i) => {
      const bar = '█'.repeat(Math.round(c.confidence * 10)) + '░'.repeat(10 - Math.round(c.confidence * 10));
      md += `### ${i + 1}. ${c.name}\n`;
      md += `- **Confidence:** ${Math.round(c.confidence * 100)}% ${bar}\n`;
      md += `- **Severity:** ${c.severity || 'Unknown'}\n`;
      md += `- **Description:** ${c.description || 'No additional description available.'}\n\n`;
    });
  } else {
    md += `No specific conditions could be confidently identified based on the provided symptoms.\n\n`;
  }
  
  md += `## Recommended Specialists\n\n`;
  if (specialties && specialties.length > 0) {
    specialties.forEach((s) => {
      md += `- ${s}\n`;
    });
  } else {
    md += `- General Physician (Primary Care)\n`;
  }
  md += `\n`;
  
  md += `## Recommended Medicines (OTC)\n\n`;
  if (medicines && medicines.length > 0) {
    medicines.forEach((m) => {
      md += `### ${m.name}\n`;
      md += `- **Dosage:** ${m.dosage || 'Follow package instructions'}\n`;
      if (m.notes) md += `- **Notes:** ${m.notes}\n`;
      md += `\n`;
    });
  } else {
    md += `No specific OTC medicines recommended. Consult a physician for prescription options.\n\n`;
  }
  
  md += `## Self-Care Recommendations\n\n`;
  if (selfCare && selfCare.length > 0) {
    selfCare.forEach((s) => {
      md += `- ${s}\n`;
    });
  } else {
    md += `- Rest and hydration\n- Monitor symptoms\n- Seek medical attention if symptoms worsen\n`;
  }
  md += `\n`;
  
  md += `## Follow-Up Instructions\n\n`;
  md += `${followUp || 'Schedule a follow-up appointment with your primary care physician if symptoms persist or worsen within 48-72 hours.'}\n\n`;
  
  md += `---\n\n`;
  
  md += `## RAG Knowledge Sources\n\n`;
  if (ragSources && ragSources.length > 0) {
    ragSources.forEach((src) => {
      md += `- **${src.disease}** (confidence: ${Math.round(src.confidence * 100)}%)\n`;
      md += `  ${src.description}\n\n`;
    });
  } else {
    md += `No specific medical knowledge sources were retrieved for this assessment.\n\n`;
  }
  
  md += `---\n\n`;
  md += `*Generated by Medisage AI Healthcare Assistant*\n`;
  md += `*This report is for educational purposes only and does not constitute medical advice.*`;
  
  return md;
};

export const generateReportJSON = (data) => {
  return {
    ...data,
    generatedAt: new Date().toISOString(),
    version: '1.0.0',
    system: 'Medisage AI Healthcare Assistant',
  };
};
