import React, { useState, useEffect } from 'react';
import { FileText, Download, CheckCircle2, Trash2, X, ChevronRight, BookOpen, Activity, AlertTriangle } from 'lucide-react';
import { getReports, downloadReportPDF, deleteReport } from '../services/api';
import { cn } from '../utils/cn';
import { SectionShell, Eyebrow, Button } from './ui';

export const MedicalReportsTab: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]);
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    getReports().then(({ data }) => {
      setReports(data || []);
    }).catch(() => setReports([])).finally(() => setLoading(false));
  }, []);

  const handleDownload = async (id: string) => {
    try {
      const res = await downloadReportPDF(id);
      const blob = new Blob([res.data], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `medical-report-${id}.md`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Download failed:', error);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this report?')) return;
    try {
      await deleteReport(id);
      setReports((prev) => prev.filter((r) => r._id !== id));
      if (selectedReport?._id === id) setSelectedReport(null);
    } catch (error) {
      console.error('Delete failed:', error);
    }
  };

  return (
    <SectionShell className="py-12 animate-fadeUp">
      <div className="mb-10 space-y-3 rounded-2xl border border-line bg-surface/70 p-8">
        <Eyebrow tone="brand"><FileText className="h-3.5 w-3.5" /> Medical Records</Eyebrow>
        <h2 className="text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Consultation Reports</h2>
        <p className="max-w-2xl text-md leading-relaxed text-ink-soft">
          View and download AI-generated medical reports from your symptom assessments. All reports include possible conditions, confidence scores, and recommended specialists.
        </p>
      </div>

      {selectedReport ? (
        <div className="mx-auto max-w-3xl space-y-6 rounded-2xl border border-line bg-raised/40 p-8">
          <div className="flex items-start justify-between border-b border-line pb-4">
            <div>
              <h3 className="text-xl font-semibold text-ink">{selectedReport.title}</h3>
              <p className="text-xs text-ink-muted">
                {new Date(selectedReport.createdAt).toLocaleString()} · Status: {selectedReport.status}
              </p>
            </div>
            <button onClick={() => setSelectedReport(null)} className="grid h-8 w-8 place-items-center rounded-full bg-white/5 text-ink-soft hover:bg-white/10 hover:text-ink">
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Disclaimer */}
          <div className="rounded-xl border border-amber-500/25 bg-amber-500/10 p-4">
            <p className="text-xs text-amber-200">
              <AlertTriangle className="h-4 w-4 inline mr-1" />
              <strong>Disclaimer:</strong> This report is generated by an AI-assisted healthcare system and is NOT a definitive medical diagnosis. Always consult a qualified healthcare professional.
            </p>
          </div>

          {/* Possible Conditions */}
          {selectedReport.possibleConditions?.length > 0 && (
            <div className="space-y-3">
              <h4 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-brand-300">
                <Activity className="h-4 w-4" /> Possible Conditions
              </h4>
              <div className="space-y-3">
                {selectedReport.possibleConditions.map((c: any, i: number) => {
                  const pct = Math.round(c.confidence * 100);
                  return (
                    <div key={i} className="rounded-xl border border-line bg-white/[0.02] p-4">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-semibold text-ink">{c.name}</span>
                        <span className={cn('text-xs font-bold',
                          c.severity === 'urgent' ? 'text-rose-300' : c.severity === 'high' ? 'text-amber-300' : 'text-emerald-300'
                        )}>{c.severity}</span>
                      </div>
                      <div className="h-2 w-full rounded-full bg-white/5 overflow-hidden">
                        <div className={cn('h-full rounded-full',
                          pct >= 70 ? 'bg-brand-400' : pct >= 40 ? 'bg-amber-400' : 'bg-ink-muted'
                        )} style={{ width: `${pct}%` }} />
                      </div>
                      <p className="mt-1 text-xs text-ink-muted">Confidence: {pct}%</p>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Recommended Specialties */}
          {selectedReport.recommendedSpecialties?.length > 0 && (
            <div className="rounded-xl border border-line bg-white/[0.02] p-4">
              <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-accent-400">Recommended Specialists</h4>
              <div className="flex flex-wrap gap-2">
                {selectedReport.recommendedSpecialties.map((s: string, i: number) => (
                  <span key={i} className="rounded-xl border border-accent-500/25 bg-accent-500/10 px-3 py-1 text-xs font-semibold text-accent-400">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Knowledge Sources */}
          {selectedReport.knowledgeSources?.length > 0 && (
            <div className="rounded-xl border border-line bg-white/[0.02] p-4">
              <h4 className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-amber-300">
                <BookOpen className="h-4 w-4" /> RAG Knowledge Sources
              </h4>
              <div className="space-y-2">
                {selectedReport.knowledgeSources.map((src: any, i: number) => (
                  <div key={i} className="flex items-center justify-between rounded-lg border border-line bg-white/[0.02] p-2">
                    <p className="text-xs font-semibold text-ink">{src.disease}</p>
                    <span className="text-xs text-brand-300">{Math.round(src.confidence * 100)}%</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Self Care */}
          {selectedReport.selfCare?.length > 0 && (
            <div className="rounded-xl border border-line bg-white/[0.02] p-4">
              <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-emerald-300">Self-Care Recommendations</h4>
              <ul className="space-y-1">
                {selectedReport.selfCare.map((s: string, i: number) => (
                  <li key={i} className="flex items-center gap-2 text-xs text-ink-soft">
                    <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" /> {s}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Doctor Notes */}
          {selectedReport.doctorDiagnosis && (
            <div className="rounded-xl border border-line bg-white/[0.02] p-4">
              <h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-ink">Doctor Diagnosis</h4>
              <p className="text-sm text-ink-soft">{selectedReport.doctorDiagnosis}</p>
              {selectedReport.doctorNotes && (
                <p className="mt-2 text-xs text-ink-muted">{selectedReport.doctorNotes}</p>
              )}
            </div>
          )}

          <div className="flex gap-3">
            <Button size="sm" onClick={() => handleDownload(selectedReport._id)}>
              <Download className="h-4 w-4" /> Download Report
            </Button>
            <Button variant="secondary" size="sm" onClick={() => handleDelete(selectedReport._id)}>
              <Trash2 className="h-4 w-4" /> Delete
            </Button>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {loading && <p className="text-sm text-ink-muted">Loading reports...</p>}
          {!loading && reports.length === 0 && (
            <div className="text-center py-12">
              <FileText className="mx-auto h-12 w-12 text-ink-muted mb-4" />
              <p className="text-sm text-ink-muted">No reports yet. Complete a symptom assessment to generate your first report.</p>
            </div>
          )}
          {reports.map((report) => (
            <button key={report._id} onClick={() => setSelectedReport(report)}
              className="w-full text-left rounded-xl border border-line bg-raised/50 p-6 transition-all hover:border-brand-400/40">
              <div className="flex items-center justify-between">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="text-sm font-semibold text-ink">{report.title}</h4>
                    <span className={cn('rounded-full px-2 py-0.5 text-[10px] font-bold',
                      report.status === 'finalized' ? 'bg-emerald-500/15 text-emerald-300' : 'bg-amber-500/15 text-amber-300'
                    )}>{report.status}</span>
                  </div>
                  <p className="text-xs text-ink-muted">
                    {new Date(report.createdAt).toLocaleDateString()} · {report.possibleConditions?.length || 0} conditions identified
                  </p>
                </div>
                <ChevronRight className="h-5 w-5 text-ink-muted" />
              </div>
            </button>
          ))}
        </div>
      )}
    </SectionShell>
  );
};
